### ISSUE TITLE
[BUG] Shortlinks to other Tenants do not work

### ISSUE THREAD

**Issue by jgough** [opensearch-project/security-dashboards-plugin#1203]
**What is the bug?**
When visiting a shortlink URL, the tenant specified in the URL seems to be ignored and it tries to load the shortlink in the current tenant.
This seems related to https://github.com/opensearch-project/security-dashboards-plugin/issues/1012

**How can one reproduce the bug?**
1. In a cluster with more than one tenant, log into Dashboards
2. Go to a page such as Discover, then click at the top Share -> Short URL -> Copy link
3. Navigate to a different Tenant
4. Open a new tab and paste the copied URL (which has a parameter `?security_tenant=first_tenant_name`
5. Note that the link does not work and the Tenant is not switched.  It attempts to load the goto URL from the 2nd Tenant selected in step 3 instead of the first tenant specified in the URL.  This results in an error

**What is the expected behavior?**
The URL should work and link to the page in the correct tenant as specified in the URL

**What is your host/environment?**
 - OS: Linux / Docker
 - Version: 2.3.0
 - Plugins: Security Plugin

**Comment by jgough** [comment]
Looks like https://github.com/opensearch-project/security-dashboards-plugin/issues/123 may be of interest here

**Comment by Leannelb** [comment]
This has been resolved on elastic search version 2.3.0.
The fix was initiated in this [PR](https://github.com/opensearch-project/security-dashboards-plugin/pull/1024) and tested in version 2.3.0. When switching tenants from a short link, the tenant is now remembered.

**Comment by jgough** [comment]
I can confirm that this bug still exists in OpenSearch 2.6.0

**Comment by Leannelb** [comment]
Thanks @jgough I can retest on 2.6.0 and implement the fix.

**Comment by leanneeliatra** [comment]
**To explain how this functionality is currently working:**

1. When a short URL (with parameter for security\_tenant) is pasted into a new tab i.e. http://localhost:5601/goto/b9da0172f96bd51ead2ee96afcca2dc2?security\_tenant=global
2. It triggers `tenant_resolver.ts` found in `plugins/security-dashboards-plugin/server/multitenancy/tenant_resolver.ts`
3. `tenant_resolver.ts` retrieves the tenant from the node backend. At this point, we now have the tenant.
4. When we come to setting up/rendering the top navigation, we fetch the tenant information again, from the front end this time. In `fetchAccountInfoSafe` we get the data of the tenant and user. Keep in mind we already have the correct tenant info from step 3. We then `fetchCurrentTenant`, getting the tenant information again, but from the frontend.
7. We go on to check if the tenant is in the URL in the function when checking if `tenantSpecifiedInUrl()`
8. The `getSavedTenant()` then fetches the tenant from the localstorage and assigns the value to `savedTenant`
9. At this stage, we were overriding the `tenant` with the value from the localstorage, `savedTenant`.
**Therefore the tenant from the URL is being over wrote with the local storage value**

**Comment by rayangou** [comment]
This bug still exists in OpenSearch 2.8.0

**Comment by lihaige01** [comment]
This bug still exists in OpenSearch 2.16.0
